### PR TITLE
use rust 2018's module system

### PR DESCRIPTION
**Pull request by anyputer**

### CODE REVIEW

**Comment by superwhiskers** [comment]
i know for a fact that the name doesn't matter, i'm just following conventions tbh

**Comment by anyputer** [comment]
it's just nicer to have this instead

**Comment by superwhiskers** [comment]
it seems way too trivial of a change and seems unnecessary. i'm already using the 2018 module system, this just takes advantage of one of the features

**Comment by anyputer** [comment]
and? just because it's small doesn't mean it can't be merged

**Comment by superwhiskers** [comment]
it seems extremely unnecessary

**Comment by superwhiskers** [comment]
nothing changes except for a file name

**Comment by anyputer** [comment]
um okay

**Pull request closed without merging**
